version: '3.4'

services:
  csc302assignments:
    image: csc302assignments
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
